### ISSUE TITLE
Use String 1024 in Sequelize

### ISSUE THREAD

**Issue by rivertam** [madhurjain/passport-local-sequelize#26] opened 2016-04-20 23:50 UTC
I just spent far too long tracking down this bug. The example given in the README is slightly incorrect; by default, Sequelize will truncate Strings to 256 characters, but this library uses hashes of size 1024. Ergo, the hashes should be specified as VARCHAR(1024).

This is a problem with the README, but this repository seems to be fairly inactive, so I mostly intend this as a warning for future developers.

**Comment by lefnire** [comment] 2016-04-22 00:48
Dupe of #21

**Comment by rivertam** [comment] 2016-04-22 02:42
Ah I guess I'm blind sorry thanks.

**Closed** 2016-04-22 02:42 UTC
